CREATE USER spa WITH encrypted password 'spa@Pa55!';
ALTER USER spa WITH SUPERUSER;
CREATE DATABASE spadb
    WITH
    OWNER = spa
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

COMMENT ON DATABASE spadb IS 'Student Progression App DB';

GRANT ALL PRIVILEGES ON DATABASE spadb TO spa;

\c spadb;

CREATE SCHEMA dev;

GRANT USAGE ON SCHEMA dev TO spa;
GRANT SELECT ON ALL TABLES IN SCHEMA dev TO spa;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA dev TO spa;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dev TO spa;

GRANT INSERT ON ALL TABLES IN SCHEMA dev TO spa;

GRANT UPDATE ON ALL TABLES IN SCHEMA dev TO spa;
GRANT UPDATE ON ALL SEQUENCES IN SCHEMA dev TO spa;

GRANT DELETE ON ALL TABLES IN SCHEMA dev TO spa;
